export const path = {
  homePage: "/",
  listProductPage: "/list-product",
  detailProductPage: "/detail-product",
  signInPage: "/signin",
  signUpPage: "/signup",
  cartItems: "/cart-item",
  cartCheckout: "/cart-checkout",
  profile: "/profile",
  wishlist: "/wishlist",
  forgotpass: "/forgot-password",
  verifyotp: "/verify-otp",
  resetpass: "/reset-password",
  address: "/manage-address",
  ordersuccess: "/order-success",
  ordertracking: "/order-tracking",
  orderhistory: "/order-history",
};
